version: "3.9"

services:
  item-db:
    # Menggunakan image mongo:3 dari Docker Hub
    image: mongo:3
    # Memakai volume bernama app-db dengan target /data/db di container
    volumes:
      - app-db:/data/db
    # Menerapkan restart policy agar container selalu restart ketika terhenti
    restart: always

  item-app:
    # Image menggunakan Container Registry Github Packages
    image: ghcr.io/wantotri/a433-microservices/item-app:v1
    # Melakukan port mapping agar dapat diakses dari port 80 di host
    ports:
      - 80:8080
    # Memastikan item-app dijalankan setelah item-db
    depends_on:
      - item-db
    # Menerapkan restart policy agar container selalu restart ketika terhenti
    restart: always

volumes:
  app-db:
